### PR TITLE
[t-mr1] Make KeyMint happy

### PR DESCRIPTION
**Pull request by bartcubbins**
Add fragment for KeyMint interfaces. Kalama uses KeyMint hardware-isolated
environment instead of Keymaster. Add required interfaces for it.
```
E android.hardware.security.keymint-service-qti: adding keymint service instance: android.hardware.security.keymint.IKeyMintDevice/default
I servicemanager: Could not find android.hardware.security.keymint.IKeyMintDevice/default in the VINTF manifest.

E android.hardware.security.keymint-service-qti: adding keymint service instance: android.hardware.security.keymint.IRemotelyProvisionedComponent/default
I servicemanager: Could not find android.hardware.security.keymint.IRemotelyProvisionedComponent/default in the VINTF manifest.

E android.hardware.security.keymint-service-qti: adding keymint service instance: android.hardware.security.secureclock.ISecureClock/default
I servicemanager: Could not find android.hardware.security.secureclock.ISecureClock/default in the VINTF manifest.

E android.hardware.security.keymint-service-qti: adding keymint service instance: android.hardware.security.sharedsecret.ISharedSecret/default
I servicemanager: Could not find android.hardware.security.sharedsecret.ISharedSecret/default in the VINTF manifest.
```

Drop Keymaster 4.1 service. libkeymaster_messages and android.hardware.keymaster@4.1
are KeyMint service dependencies so they were left.

Test: boot with userdata encryption enabled to home,
screen lock PIN code is set, device is locked/unlocked.

### CODE REVIEW

**Comment by MarijnS95** [comment]
> libkeymaster_messages and android.hardware.keymaster@4.1 are KeyMint service dependencies so they were left.

KeyMint communicates with these over something else that's not binder/HIDL?

EDIT: For `android.hardware.keymaster@4.1` you mean just the vendor helper library generated from HIDL (the `android.hardware.keymaster@4.1.vendor` target)? That seems funky.

**Comment by bartcubbins** [comment]
```
01-01 00:00:02.893     0     0 I init    : starting service 'vendor.keymint-qti'...
--------- beginning of crash
01-01 00:00:02.894   543   543 F linker  : CANNOT LINK EXECUTABLE "/odm/bin/hw/android.hardware.security.keymint-service-qti": library "android.hardware.keymaster@4.0.so" not found: needed by main executable
01-01 00:00:02.897     0     0 I init    : Service 'vendor.keymint-qti' (pid 543) exited with status 1
```

**Comment by MarijnS95** [comment]
Maybe the new KeyMint service (optionally, via e.g. a prop) also hosts the "legacy" keymaster service?

**Comment by bartcubbins** [comment]
we can get some information under the hood by looking at this repo
https://android.googlesource.com/platform/system/core/+/refs/heads/main/trusty/keymaster/keymint/

**Comment by MarijnS95** [comment]
That's probably less modified than what Qcom built.

https://android.googlesource.com/platform/system/core/+/refs/heads/main/trusty/keymaster/Android.bp only the keymaster executables depend on the vendor HAL. We should perhaps look at the symbol table to see if it uses anything explicitly at all, or accidentally/indirectly through a random library.

**Pull request merged**
